# yaml-language-server: $schema=https://raw.githubusercontent.com/nf-core/modules/master/modules/meta-schema.json
name: "gfa2fa"
description: Convert GFA (Graphical Fragment Assembly) format to FASTA format
keywords:
  - assembly
  - conversion
  - gfa
  - fasta
tools:
  - gawk:
      description: GNU implementation of the AWK programming language
      homepage: https://www.gnu.org/software/gawk/
      documentation: https://www.gnu.org/software/gawk/manual/
      licence: ["GPL v3"]
      identifier: ""

input:
  - - meta:
        type: map
        description: |
          Groovy Map containing sample information
          e.g. `[ id:'sample1' ]`
    - gfa:
        type: file
        description: GFA format assembly file
        pattern: "*.gfa"

output:
  - fasta:
      - meta:
          type: map
          description: |
            Groovy Map containing sample information
            e.g. `[ id:'sample1' ]`
      - "*.fa":
          type: file
          description: FASTA format assembly file
          pattern: "*.fa"
  - versions:
      - versions.yml:
          type: file
          description: File containing software versions
          pattern: "versions.yml"

authors:
  - "@SeqeraAI"
maintainers:
  - "@SeqeraAI"
