name: qc_plots
description: Generate QC plots for integration site analysis
keywords:
  - qc
  - visualization
  - plots
  - integration
tools:
  - python:
      description: Python programming language
      homepage: https://www.python.org/
      documentation: https://docs.python.org/3/
      tool_dev_url: https://github.com/python/cpython
      licence: ['PSF']
  - matplotlib:
      description: Plotting library for Python
      homepage: https://matplotlib.org/
      documentation: https://matplotlib.org/stable/contents.html
      licence: ['PSF']
input:
  - meta:
      type: map
      description: |
        Groovy Map containing sample information
        e.g. [id: 'sample1']
  - paf:
      type: file
      description: PAF alignment file from minimap2
      pattern: "*.paf"
  - integration_sites:
      type: file
      description: Integration sites file (chr\tpos format)
      pattern: "*.{txt,bed,tsv}"
output:
  - meta:
      type: map
      description: |
        Groovy Map containing sample information
        e.g. [id: 'sample1']
  - plots:
      type: file
      description: QC plots in PNG format
      pattern: "*.png"
  - versions:
      type: file
      description: File containing software versions
      pattern: "versions.yml"
authors:
  - "@username"
